module.exports.descriptors = [
    'Rambling',
    'The Wagon',
    'The Ghost',
    'Exotic',
    'Rusty Spoon',
    'Kegs and Kittens',
    'Moody Afternoon',
    'Daze',
    'The Regal',
    'The Overton',
    'Copper',
    'Pours',
    'Daybreak',
    'Sundown',
    'Sharkeys Seaside',
    'Spirit',
    'Two Wheels',
    'La Caretta'
];

// module.exports.places = [
//     'Flats',
//     'Village',
//     'Canyon',
//     'Pond',
//     'Group Camp',
//     'Horse Camp',
//     'Ghost Town',
//     'Camp',
//     'Dispersed Camp',
//     'Backcountry',
//     'River',
//     'Creek',
//     'Creekside',
//     'Bay',
//     'Spring',
//     'Bayshore',
//     'Sands',
//     'Mule Camp',
//     'Hunting Camp',
//     'Cliffs',
//     'Hollow'
// ];

module.exports.places = [
    'Pub',
    'Tavern',
    'Bar',
    'Inn',
    'Public House',
    'Taproom',
    'Brewery',
    'Speakeasy',
];